### ISSUE TITLE
Client makes no use of MQTT

### ISSUE THREAD

**Issue by eepgwde** [NickJokic/mqtt-realtime-chart-client#1]
I was looking at the sockets and messages flows and it seems that you haven't used MQTT for data at all. You use Vue to connect the browser directly to the 3000 socket offered by the server.

The server publishes on the MQTT channel. 

I thought the architecture would be for the server to publish to MQTT and the client to subscribe and then ticker the data it receives.

**Comment by NickJokic** [comment]
Hi,

I am not sure what exactly do you mean.

This is a MQTT simulation, where the server is both the **publisher** and the **subscriber**. The messages are then emitted via WebSockets and the app-client reads from those.

Why do you think should the client directly subscribe to the MQTT channel? In a real-project scenario, MQTT would have multiple layers of security (e.g. auth), which is always preferred to be done via the server side.

Do you have any reasons, why the client should connect directly to the MQTT broker?

P.S.: you can modify the code to suit your needs. The MQTT.js library should also work in the browser, if I'm not wrong.

Best Regards,
Nick

**Comment by eepgwde** [comment]
Thanks, yes I understand the architecture could work like that.

I was hoping the client would directly subscribe and display without using
a websockets feed.

I don't know Vue, I thought you might have chosen to use websockets because
it is some restriction on Vue.

Thanks.

**Comment by NickJokic** [comment]
It's all JS so what ever you can do with Vanilla JS you can also do with Vue.

Take a look at [MQTT.js](https://www.npmjs.com/package/mqtt) and try to implement it in the client and connect directly to the broker.

Best of luck,
Nick
